<a href="https://colab.research.google.com/github/yogeshns1924/python-practices-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
numbers = np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [ ]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
b=np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [ ]:
c=np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [ ]:
a=np.arange(2,21,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
numbers = np.array([10,20,30,40,50])
print(numbers.size)

5


In [ ]:
import numpy as np

num = np.array([[12, 34, 56, 77, 67],
              [45, 56, 7, 7, 8],] )

print(num.shape)
print(num.ndim)

(2, 5)
2


In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print(a)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
arr = np.array([15,8,25,10,30])
print(arr)
print(arr.max())
print(arr.min())

[15  8 25 10 30]
30
8


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.sum())
print(arr.mean())

[10 20 30 40 50]
150
30.0


In [ ]:
arr=np.array([10,20,30,40])
print(arr.argmax())

3


In [ ]:
import numpy as np
d = np.array([100,200,300,400,500])
print(d)
print(d[0])
print(d[2])
print(d[-1])

[100 200 300 400 500]
100
300
500


In [ ]:
d = np.array([100,200,300,400,500])
print(d[::-1])

[500 400 300 200 100]


In [ ]:
d = np.array([100,200,300,400,500])
print(d[:3])

[100 200 300]


In [ ]:
import numpy as np
arr = np.array([
    [1, 2, 3,5],
    [5, 6, 7 ,8]
])

print("rows:",arr.shape[0])
print( "columns:",arr.shape[1])

rows: 2
columns: 4


In [ ]:
arr = np.arange(1, 21)

print(arr[arr % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
import numpy as np

arr = np.array([10, 60, 30, 80, 40, 90])

arr[arr > 50] = 0

print(arr)

[10  0 30  0 40  0]


In [ ]:
arr = np.array([10,30,15,40,20,50])
print(arr)
print(arr[arr > 25])

[10 30 15 40 20 50]
[30 40 50]


In [ ]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [ ]:
arr=np.array([2,4,6,8,10])
print(arr**2)



[  4  16  36  64 100]


In [ ]:
arr=np.array([4,16,25,9])
print(np.sqrt(arr))

[2. 4. 5. 3.]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0


In [ ]:
import numpy as np
a = np.array([[2,3,4],
               [4,5,6],
               [1,3,5,]])
print(a)
print(a.sum(axis=1))



[[2 3 4]
 [4 5 6]
 [1 3 5]]
[ 9 15  9]


In [ ]:
a = np.array([[2,3,4],
               [4,5,6],
               [1,3,5,]])
print(a)
print(a.sum(axis=0))

[[2 3 4]
 [4 5 6]
 [1 3 5]]
[ 7 11 15]


In [ ]:
a = np.array([[2,3,4],
               [4,5,6]])
print(a)
print(a.max(axis=1))

[[2 3 4]
 [4 5 6]]
[4 6]


In [ ]:
a = np.array([[20,3,4],
               [4,50,6]])
print(a)
print(a.min(axis=0))

[[20  3  4]
 [ 4 50  6]]
[4 3 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = arr.reshape(2, 3)

print(newarr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.flatten())

[1 2 3 4 5 6]


In [ ]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print(a @ b)

[[19 22]
 [43 50]]


In [ ]:
import numpy as np
marks = np.array([45, 78, 92, 35, 88, 67, 30, 95])
print("Marks:",marks)
print("student above 60:",marks[marks > 60])
print("max:",marks.max())
print("min:",marks.min())
print("avg:",marks.mean())
print(len(marks[marks > 60]))

Marks: [45 78 92 35 88 67 30 95]
student above 60: [78 92 88 67 95]
max: 95
min: 30
avg: 66.25
5
